package at.tree.challenge.exception

class LoopException : RuntimeException()
